### ISSUE TITLE
Is it possible to use BigSur IPSW?

### ISSUE THREAD

**Issue by iVoider** [KhaosT/MacVM#6]
Or only Monterey can be virtualised?

**Comment by kode54** [comment]
From what I've gathered from a fellow developer, macOS for M1 neither has a software renderer/compositor, nor does anything before Monterey support the paravirtualized GPU that Virtualization.framework provides for macOS VMs. So this VM solution is literally only "Monterey or newer, running on a Monterey or newer host".

Which is really all you get on macOS anyway, because macOS doesn't support jails or containers, only virtual machines. Better than nothing, eh?

**Comment by KhaosT** [comment]
Big Sur is not supported as the ipsw lacks compatible kernel for the macOS VM.
